[package]
name = "since"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
tokio = { version = "1.29.1", features = ["macros", "process", "rt-multi-thread"] }

gitup = { path = "../gitup" }
